### ISSUE TITLE
Unable to copy file to created ec2 Instance

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/AWSIssues#53]
<img width="549" alt="6" src="https://user-images.githubusercontent.com/58015684/69537754-c73ef080-0fa6-11ea-8481-27ef91b9b8fc.PNG">

**Comment by srmanikanta** [comment]
sir I think your practise.pem file is not avialable in your machine 
if available please give that path.
Tip: check your practise.pem file is available or not use the below command 
#ls

**Comment by Jagannath92** [comment]
<img width="453" alt="7" src="https://user-images.githubusercontent.com/58015684/69789909-75d17400-11e7-11ea-9df9-af881caed90d.PNG">
File practise.pem their in my downloads folder. Attached the screenshot

**Comment by srmanikanta** [comment]
sir previously you are tying to copy the practise.pem from ec2 to ec2 (linux-linux)  machine but your practise.pem  is in your download folder in windows.
* if you copy the practise.pem from windows to linux(ec2) machine execute the below command
  syntax:
   scp -i pemfile sourcefile  destinationuser@destinationip:destinationdirectory
example: 
   $scp -i practise.pem practise.pem ec2-user@13.126.75.60:/home/ec2-user
the above command copies the practise.pem from your windows to linux
in the same way copy your practise.pem from your ec2  machine to ec2 machine
first check the key is present in your path or not if practise.pem is present in your current path give a relative path at the time of scp otherwise give complete path
Note: in your case the practise.pem file is not in yout current path that's way it shows an error.
I think it is useful to you if not please ignore.
if you got the answer from above error please close the issue.

**Comment by Jagannath92** [comment]
tried in same way it not working please have a look once again, thankyou

**Comment by srmanikanta** [comment]
if you didn't solve the issue still please call this 6305969526 number
