### ISSUE TITLE
AWS Migrations  reminders  from my  side 

### ISSUE THREAD

**Issue by Mohan007177** [QT-DevOps/AWSIssues#69]
AWS  Migrations  Topic  Exceptions  
Need  from   Sir Migration scenarios / Examples 

1)oN PRIME hyper  ----to--  AWS 

2)ON PEIME VMWARE  --- to ---  AWS 

3) ON PRIME  DATABASE (oracle/sql --- to  AWS  CLOUD Maria DB/any  DB )

4)  azure/google cloud    to -----  AWS  CLOUD   steps  one by one  3rd party  Tools like  Cloud  Endure .. etc  Samples / Examples 

Mitigation  steps by  steps (  document  ref links  )

clearly  i am exception  from AWS Migration  Topics 

vm  to  vm  migrations 
VM + applications   

ThanksMohan Reddy

**Comment by srmanikanta** [comment]
Hi, mohan reddy
Migration topics: 
Physical to Amazon EC2
VMs on Hyper-V to EC2
VMs on VmWare ESXI to EC2
Database Migration

####  if you have less number of vm's to do  migration for above topics the  approach is
* First convert your vm's into some format(like .ova,ovf,vmdk,vhd)
* create a s3 bucket and upload the ova file 
*  import the image 
* create the ec2(virtual machine) 

#### if you have a huge number of vm's  to do  migration for above topics the approach is
*  first setup hyper or vmware esxi (because the setup is existed physically on your organization but we don't have a physicla setup that is way we setup by own)
* to know the setup please follow the official documentation whereever sir provide the links for documentation 

I think this is used to you for understanding if not please leave and mention where you stuck
if this is useful to you please close the issue.

Note: Follow the aws documentation

**Comment by tejarajaboina** [comment]
Manikanta nice explanation on higher level
