### ISSUE TITLE
RDP not supported on Windows Home Edition

### ISSUE THREAD

**Issue by AmrishPopat** [QT-DevOps/AWSIssues#74]
I created a T2 Large Machine and download the RDP file, While opening the RDP file in My Windows Home Edition, I get the below error. Also when I turn on RDP it says, RDP not available for Windows Home Edition

![image](https://user-images.githubusercontent.com/53220082/73859859-a27eb900-4832-11ea-94a3-ab9622f4a8f6.png)

![image](https://user-images.githubusercontent.com/53220082/73859927-b9251000-4832-11ea-909e-7ac18e90a55a.png)

**Comment by ABBANAPURI0445** [comment]
port issue may be 
enable 9989 RDP

**Comment by srmanikanta** [comment]
There is no Remote Desktop in Windows 10 Home. Since it was for home usage, Microsoft removed some features from Windows 10 home like group policy editor gpedit.msc and remote desktop RDP. These features are only available in the Pro and Enterprise editions.

Note: This is not a port issue. Actually rdp port is 3389.

**Comment by NareshAbbanapuri** [comment]
yeah port 3389
please upgrade to professional

**Comment by shaikkhajaibrahim** [comment]
We can't be able to help bcoz of license related issues
